CONTIKI_PROJECT = ble-beacon
all: $(CONTIKI_PROJECT)

PLATFORMS_ONLY = simplelink keystone

CONTIKI=../../../..

# Specific additional source files beyond 'CONTIKI_PROJECT'
# PROJECT_SOURCEFILES += <file.c>

# Enable the interactive shell console on the UART
MODULES += os/services/shell 

include $(CONTIKI)/Makefile.include
